# Create release of a course. This script should be placed in .github/workflows folder inside of the course repo
# To create a release, create and push a new tag like so:
# git tag v1.0.0 && git push --tags
# Or, in github repo, go to Actions > Create a Release > Run Workflow
# To make this workflow work, make sure to go to repo Settings > Actions > General > Workflow permissions and set it to "Read and Write permissions"
name: Create a Release

on:
  workflow_dispatch:
  push:
    tags:
    # Trigger the workflow when a tag with the format 'v*' is pushed, like so:
    # git tag v1.0.0 && git push --tags
      - 'v*'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Clone the course processing script repo, install packages, and run it.
      # - name: Setup Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 18

      # - name: Clone script repository
      #   run: git clone https://github.com/lumenwrites/process-course

      # - name: Install dependencies
      #   working-directory: process-course
      #   run: |
      #     npm ci
      #     npm run start
      # - name: Run course processing script

      # Download and run the course processing script
      # It will process the course, zip it, and output it into ./content-gdschool-releases/ folder
      - name: Download and extract compiled script
        run: |
          wget https://github.com/lumenwrites/process-course/releases/download/v1.0.0/process-course-linux -O process-course
          chmod +x process-course
  
      - name: Run compiled script
        run: |
          ./process-course

      - name: Generate Changelog
        run: |
          export TAG_VERSION="${GITHUB_REF#refs/*/}"
          export TAG_MESSAGE=$(git tag -l --format='%(contents:subject)' $TAG_VERSION)
          export COMMIT_SHA="${{ github.sha }}"
          export FILE="${{ github.workspace }}-CHANGELOG.txt"
          echo "# Learn to Code for Godot" > $FILE
          echo "commit: $COMMIT_SHA" >> $FILE
          echo "$TAG_VERSION: $TAG_MESSAGE" >> $FILE
          echo "" >> $FILE
          ls content-gdschool-releases/*.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          append_body: true
          files: |
            content-gdschool-releases/*.zip
          body_path: ${{ github.workspace }}-CHANGELOG.txt